from datetime import date
from polarlib.polar.news_corpus_collector import *


OUTPUT_DIR = "Olympics_jan_june"  

if __name__ == "__main__":

    '''
        # Core Olympic and general terms
        master_keywords = [
            "olympics",
            "olympic",
            "paris2024",
            "paris 2024",
            "olympic games",
            "summer olympics",
            "olympiad 2024",
            "games 2024",
            "olympic news",
            "olympic medal",
            "medal count",
            "medal",
            "results 2024",
            "schedule 2024",
            "opening ceremony",
            "closing ceremony",
            "olympic torch",
            "olympic village",
            "IOC",
        ]

        # sports & events
        sports_keywords = [
            "athletics",
            "100 meters",
            "200 meters",
            "400 meters",
            "800 meters",
            "1500 meters",
            "5000 meters",
            "10000 meters",
            "marathon",
            "110 meter hurdles",
            "400 meter hurdles",
            "3000 meter steeplechase",
            "high jump",
            "long jump",
            "triple jump",
            "pole vault",
            "shot put",
            "discus throw",
            "hammer throw",
            "javelin throw",
            "decathlon",
            "heptathlon",
            "swimming",
            "50m freestyle",
            "100m freestyle",
            "200m freestyle",
            "400m freestyle",
            "800m freestyle",
            "1500m freestyle",
            "100m butterfly",
            "200m butterfly",
            "100m backstroke",
            "200m backstroke",
            "100m breaststroke",
            "200m breaststroke",
            "4x100m relay",
            "4x200m relay",
            "medley relay",
            "open water swimming",
            "gymnastics",
            "artistic gymnastics",
            "rhythmic gymnastics",
            "trampoline",
            "balance beam",
            "vault",
            "floor exercise",
            "uneven bars",
            "parallel bars",
            "pommel horse",
            "rings",
            "basketball",
            "3x3 basketball",
            "football",
            "tennis",
            "volleyball",
            "beach volleyball",
            "cycling",
            "road cycling",
            "track cycling",
            "mountain biking",
            "bmx racing",
            "bmx freestyle",
            "boxing",
            "wrestling",
            "greco-roman wrestling",
            "freestyle wrestling",
            "judo",
            "fencing",
            "archery",
            "rowing",
            "canoeing",
            "kayak slalom",
            "canoe sprint",
            "sailing",
            "skateboarding",
            "surfing",
            "climbing",
            "sport climbing",
            "breakdancing",
            "triathlon",
            "hockey",
            "rugby",
            "rugby sevens",
            "baseball",
            "softball",
            "table tennis",
            "badminton",
            "weightlifting",
            "diving",
            "shooting",
            "golf",
            "equestrian",
            "dressage",
            "show jumping",
            "eventing",
            "modern pentathlon"
        ]

        # controversies & polarization
        controversy_keywords = [
            "boycott",
            "protest",
            "scandal",
            "outrage",
            "backlash",
            "ban",
            "doping",
            "corruption",
            "cheating",
            "referee",
            "var",
            "judging",
            "controversy",
            "politics in sports"
        ]

        # gender & inclusion
        gender_keywords = [
            "transgender",
            "trans athlete",
            "gender",
            "inclusion",
            "equality",
            "lgbtq",
            "fairness",
            "women’s sports"
        ]

        # participating countries
        countries = [
            "afghanistan",
            "albania",
            "algeria",
            "american samoa",
            "andorra",
            "angola",
            "antigua and barbuda",
            "argentina",
            "armenia",
            "aruba",
            "australia",
            "austria",
            "azerbaijan",
            "bahamas",
            "bahrain",
            "bangladesh",
            "barbados",
            "belgium",
            "belize",
            "benin",
            "bermuda",
            "bhutan",
            "bolivia",
            "bosnia and herzegovina",
            "botswana",
            "brazil",
            "brunei",
            "bulgaria",
            "burkina faso",
            "burundi",
            "cabo verde",
            "cambodia",
            "cameroon",
            "canada",
            "cape verde",
            "cayman islands",
            "central african republic",
            "chad",
            "chile",
            "china",
            "chinese taipei",
            "colombia",
            "comoros",
            "congo (republic of the)",
            "congo (democratic rep.)",
            "cook islands",
            "costa rica",
            "côte d’ivoire",
            "croatia",
            "cuba",
            "cyprus",
            "czech republic",
            "denmark",
            "djibouti",
            "dominica",
            "dominican republic",
            "ecuador",
            "egypt",
            "el salvador",
            "equatorial guinea",
            "eritrea",
            "estonia",
            "eswatini",
            "ethiopia",
            "federated states of micronesia",
            "fiji",
            "finland",
            "france",
            "gabon",
            "gambia",
            "georgia",
            "germany",
            "ghana",
            "great britain",
            "greece",
            "grenada",
            "guam",
            "guatemala",
            "guinea",
            "guinea-bissau",
            "guyana",
            "haiti",
            "honduras",
            "hong kong",
            "hungary",
            "iceland",
            "india",
            "indonesia",
            "iran",
            "iraq",
            "ireland",
            "israel",
            "italy",
            "jamaica",
            "japan",
            "jordan",
            "kazakhstan",
            "kenya",
            "kiribati",
            "kosovo",
            "kuwait",
            "kyrgyzstan",
            "laos",
            "latvia",
            "lebanon",
            "lesotho",
            "liberia",
            "libya",
            "liechtenstein",
            "lithuania",
            "luxembourg",
            "madagascar",
            "malawi",
            "malaysia",
            "maldives",
            "mali",
            "malta",
            "marshall islands",
            "mauritania",
            "mauritius",
            "mexico",
            "moldova",
            "monaco",
            "mongolia",
            "montenegro",
            "morocco",
            "mozambique",
            "myanmar",
            "namibia",
            "nauru",
            "nepal",
            "netherlands",
            "new zealand",
            "nicaragua",
            "niger",
            "nigeria",
            "north macedonia",
            "norway",
            "oman",
            "pakistan",
            "palau",
            "palestine",
            "panama",
            "papua new guinea",
            "paraguay",
            "peru",
            "philippines",
            "poland",
            "portugal",
            "puerto rico",
            "qatar",
            "romania",
            "rwanda",
            "saint kitts and nevis",
            "saint lucia",
            "saint vincent and the grenadines",
            "samoa",
            "san marino",
            "são tomé and príncipe",
            "saudi arabia",
            "senegal",
            "serbia",
            "seychelles",
            "sierra leone",
            "singapore",
            "slovakia",
            "slovenia",
            "solomon islands",
            "somalia",
            "south africa",
            "south korea",
            "south sudan",
            "spain",
            "sri lanka",
            "sudan",
            "suriname",
            "sweden",
            "switzerland",
            "syria",
            "tajikistan",
            "tanzania",
            "thailand",
            "togo",
            "tonga",
            "trinidad and tobago",
            "tunisia",
            "turkey",
            "turkmenistan",
            "tuvalu",
            "uganda",
            "ukraine",
            "united arab emirates",
            "united states of america",
            "uruguay",
            "uzbekistan",
            "vanuatu",
            "venezuela",
            "vietnam",
            "virgin islands",
            "yemen",
            "zambia",
            "zimbabwe",
            "individual neutral athletes"
        ]

        # base olympic terms
        base_terms = [
            "olympics",
            "paris 2024",
            "olympic games",
            "medal",
            "athlete",
            "team",
            "gold",
            "silver",
            "bronze",
            "olympic results"
        ]

        # Combine countries with Olympic terms
        country_combinations = [f"{country} {term}" for country in countries for term in base_terms]

        # Merge all into a single master list
        master_keywords.extend(sports_keywords)
        master_keywords.extend(controversy_keywords)
        master_keywords.extend(gender_keywords)
        master_keywords.extend(country_combinations)

        # Remove duplicates just in case
        master_keywords = list(set(master_keywords))
    '''
        # Create collector
    
    master_keywords=[
            "olympics",
            "olympic",
    ]
    
    corpus_collector = NewsCorpusCollector(
        output_dir = OUTPUT_DIR,
        from_date = date(year=2024, month=1, day=1),
        to_date = date(year=2024, month=5, day=23),
        keywords = master_keywords
    )

    corpus_collector.collect_archives()
    corpus_collector.collect_articles() 
    corpus_collector.pre_process_articles()


